name: Github Actions test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build_job:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Login to Docker hub 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password:  ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker build and push image
        uses: docker/build-push-action@v6.9.0
        with:
          file: ./Dockerfile
          push: true
          tags: sara933/ts-proj:v-${{github.run_attempt}}

  deploy_job:
    runs-on: 'ubuntu-latest'
    needs: build_job
    steps:
      - name: SSH to server
        run : |
          ssh -o StrictHostKeyChecking=no -i ${{secrets.SSH_KEY}} ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} << EOF
            docker pull sara933/ts-proj:v-${{github.run_attempt}}
            docker run -d -p 80:80 sara933/ts-proj:v-${{github.run_attempt}}
            exit
          EOF
      
